algoritmo "Operadores Relacionais"
var
    A, B, C: inteiro
inicio
    A <- 2
    B <- 3
    C <- 5
    Escreval (A>B) // A é maior que B?
    Escreval (A=B) // A é igual a B?
    Escreval (A<>B) // A é diferente de B?
    Escreval (A>2) // A é maior que 2?
    Escreval (A>=2) // A é maior ou igual a 2?   
    Escreval (C+A+B) // C é maior que A+B?   
    Escreval (C>=B^A) // C é maior ou igual a B elevado a A?
    Escreval (C<=B^A) // C é menor ou igual a B elevado a A?

fimalgoritmo